### PR TITLE
Prefix SCSS partial filenames with underscore

### PR DESCRIPTION
**Pull request by osxi**
Partials that are to be imported as part of a generated file should be prefixed with an underscore.

### CODE REVIEW

**Comment by DanielOchoa** [comment]
[I believe ember-cli expects all files to not have underscores](https://github.com/stefanpenner/ember-cli/issues/879). Although, I'm not sure for css files since they do compile without warnings. @jakecraige what do you think about this?

**Comment by osxi** [comment]
That issue references template partials for ember-cli. Sass partials should be prefixed with an underscore so that they are ignored until imported, and therefore will not generate a standalone file but will be included elsewhere (in our case, `__name__.scss` will import `_base.scss` but a base.css should not be generated on it's own).

The way ember-cli-proto-css is right now, a CSS file will be generated for every SCSS file without an underscore prefix. This is not desired and if I'm not mistaken, prevents `__name__.scss` from having access to the contents of other files, such as variables defined in `variables.scss`.

References: http://zurb.com/university/lessons/35 and http://sass-lang.com/documentation/file.SASS_REFERENCE.html#partials

**Comment by DanielOchoa** [comment]
Just tested it. You are correct sir.

**Comment by jakecraige** [comment]
@osxi ember cli is only going to compile a single output file in app.css, it doesn't care how many file you have. Just recently the ability to output more than a single file was added, you have to explicitly define it though. Having files in the styles directory won't automatically output extra files. 

I'm not sure how I feel about this actually. I think the convention is nice, but adopting this convention means that literally every file we have in that directory would be underscored since no file except the main app.css will be output, and that feels a little funny, lol

**Comment by DanielOchoa** [comment]
From looking at the dist/assets directory, I can see that each .scss file under styles gets compiled into its own css file if not prepended with _. 

So there is duplication because that file is already included in the **appName**.css yet still gets generated. Prefixing the file with _ solves this.

**Comment by DanielOchoa** [comment]
I assume this is the behavior for using ember-cli-sass and not broccoli-sass. 

_EDIT:_ Can confirm, broccoli-sass compiles all .scss files into one, whereas ember-cli-sass will compile multiple .css files unless the file is prepended by _

**Comment by jakecraige** [comment]
Interesting... Good to know. Cool cool cool

**Comment by osxi** [comment]
Good to know that ember-cli-sass is doing it the right way :+1:

**Pull request merged**
